import type { Metadata } from "next";
import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/Footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${poppins.variable} antialiased overflow-x-hidden`}
      >
        <header className="fixed left-0 right-0 top-0 z-[9999] w-full">
          <Navbar />
        </header>
        <div className="pt-[72px] md:pt-[84px]">
          {children}
        </div>
        <footer className="w-full">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
